name: Automation build images
run-name: ${{ github.event.head_commit.message }}

on:
  push:
    tags:
      - 'v*'

jobs:
  build-app:
    name: "Build React App into Distributable"
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install nodejs deps
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: dist/

  release-app:
    name: "Release builded app"
    needs: build-app
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-result
          path: dist
      - name: Compress artifact
        run: cd dist && zip -r ../one-app.zip .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: one-app.zip

  build-docker-image:
    name: "Build Docker image"
    needs: release-app
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login ghcr.io
        run: echo -n "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build . \
            -t ghcr.io/${{ github.repository }}:latest \
            -t ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Push to ghcr.io
        run: docker push --all-tags ghcr.io/${{ github.repository }}

  deploy-image:
    name: "Deploy image into server"
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Pull image from ghcr and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd ~/app
            docker compose pull frontend
            docker compose up -d frontend